import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { AlertTriangle, Baby, CalendarDays, Check, ChevronDown, Clock3, Droplets, Eye, Heart, HeartPulse, Home, Mail, MapPin, Menu, MessageCircle, PawPrint, Phone, PillBottle, Play, ShieldCheck, Syringe, Thermometer, Users, X } from 'lucide-react';
import './real.css';

const supabase = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY
  ? createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY)
  : null;

const nav = [
  ['home', 'Home'], ['learn', 'What Is Hypoglycemia'], ['emergency', 'Emergency Steps'],
  ['prevention', 'Prevention'], ['aftercare', 'Aftercare'], ['faq', 'FAQ'], ['contact', 'Contact'],
];

const hero = {
  home: ['Pup-Lift:', 'Emergency Support\nfor Hypoglycemia Episodes', 'Fast, calm guidance for Chihuahua owners when a puppy becomes weak, limp, cold, shaky, or unresponsive.', 'Created for tiny hearts. Backed by experience.'],
  learn: ['What Is Hypoglycemia?', 'Tiny puppies can drop fast.', 'Hypoglycemia is dangerously low blood sugar. In toy puppies, especially Chihuahuas, it can happen suddenly and become life-threatening without prompt action.', 'Know the signs. Act with love.'],
  emergency: ['Emergency Steps', 'What to do when your puppy is\nweak, cold, shaky, collapsed, or unresponsive.', 'Fast action can save your puppy’s life. Stay calm, warm your puppy, apply Pup-Lift to the gums or under the tongue, and monitor closely while you prepare to contact your veterinarian.', ''],
  prevention: ['Prevention', 'How to help prevent hypoglycemia\nbefore it starts.', 'Most hypoglycemia episodes can be reduced or prevented through careful feeding, warmth, observation, reduced stress, and close attention to tiny puppies.', ''],
  aftercare: ['Aftercare', 'What to do after your puppy\nbegins to respond.', 'Once your puppy perks up, recovery is not over yet. Continue close care with monitoring, warmth, feeding, hydration, and watching for any signs that symptoms may return.', ''],
  faq: ['FAQ', 'We’re Here to Help', 'Find quick answers to the most common questions about hypoglycemia and using Pup-Lift. Can’t find what you need? Contact our team.', 'Knowledge. Preparedness. Peace of Mind.'],
  contact: ['Contact Us', 'We Care. We Listen.', 'Have a question about Pup-Lift, hypoglycemia, or your puppy’s health and care? We’re here to help and happy to support you every step of the way.', 'We’re Here for You. Always.'],
};

function App() {
  const [page, setPage] = useState('home');
  const [menu, setMenu] = useState(false);
  const go = (id) => { setPage(id); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <div className="site"><Header page={page} go={go} menu={menu} setMenu={setMenu}/><main><Hero page={page} go={go}/>{page==='home'&&<HomePage go={go}/>} {page==='learn'&&<LearnPage go={go}/>} {page==='emergency'&&<EmergencyPage go={go}/>} {page==='prevention'&&<PreventionPage go={go}/>} {page==='aftercare'&&<AftercarePage go={go}/>} {page==='faq'&&<FAQPage go={go}/>} {page==='contact'&&<ContactPage/>}</main><Footer page={page} go={go}/></div>;
}

function Header({ page, go, menu, setMenu }) {
  const swva = page === 'faq' || page === 'contact';
  return <header className="top"><button className="brand" onClick={()=>go('home')}><Logo swva={swva}/></button><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button><nav className={menu?'open':''}>{nav.map(([id,label])=><button key={id} onClick={()=>go(id)} className={page===id?'active':''}>{label}</button>)}</nav><div className="top-actions"><button className="pill dark" onClick={()=>go('emergency')}>Emergency Steps <Heart size={15}/></button><button className="pill light" onClick={()=>go('contact')}>SWVA Chihuahua <Heart size={15}/></button></div></header>;
}

function Logo({ swva }) { return <div className={swva?'logo swva':'logo'}><div className="logo-mark">{swva?<DogLine/>:<PawPrint size={34}/>}</div><div><strong>{swva?'Southwest Virginia':'Pup-'}<em>{swva?'Chihuahua':'Lift'}</em></strong>{!swva&&<span>Emergency Support<br/>for Tiny Hearts</span>}{swva&&<span>Chihuahua</span>}</div></div>; }
function DogLine(){return <svg width="54" height="38" viewBox="0 0 80 52" fill="none"><path d="M9 33V19l8-7 8 7h13l6-10 7 11 12 3 6 10-7 5H45l-5 8-5-8H21l-4 7-4-7H9Z" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><path d="M61 24l8-10M22 19l-6-10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>}
function QR(){return <div className="qr">{Array.from({length:49}).map((_,i)=><i key={i} className={(i*7+i%5)%3===0?'on':''}/>)}</div>}
function Puppy(){return <div className="puppy"><div className="ear l"/><div className="ear r"/><div className="head"><i/><i/><div className="muzzle"><b/><span/></div></div><div className="body"><em/><em/></div></div>}
function Bottle(){return <div className="bottle"><div className="cap"/><div className="label"><PawPrint size={18}/><b>Pup-<em>Lift</em></b><span>For Puppies</span><small>Fast absorption<br/>oral care support</small><QR/></div></div>}

function Hero({ page, go }) {
  const h = hero[page]; const simple = page === 'faq' || page === 'contact';
  return <section className="hero"><div className="hero-copy">{h[3]&&<p className="kicker">{h[3]} <Heart size={14}/></p>}<h1>{h[0]}<span>{h[1]}</span></h1><p className="lede">{h[2]}</p><div className="buttons">{page!=='contact'&&<button className="btn primary" onClick={()=>go(page==='faq'?'contact':'emergency')}><Heart/> {page==='faq'?'Contact Our Team':'Start Emergency Steps'}</button>}{!simple&&<button className="btn secondary" onClick={()=>go(page==='home'?'prevention':'contact')}>{page==='home'?'Learn Prevention':'When to Call the Vet'} →</button>}</div>{!simple&&<div className="micro"><Mini icon={Clock3} title="Act within minutes" text="Early action makes the biggest difference."/><Mini icon={Heart} title="Warmth matters" text="Gentle warmth helps stabilize."/><Mini icon={Syringe} title="Small amounts" text="Tiny amounts can be repeated."/></div>}</div><div className="scene"><div className="blanket"/><Puppy/><Bottle/><div className="scan"><strong>{simple?'Scan Anytime.':'Puppy unresponsive?'}<br/>{simple?'Be Prepared.':'Start here.'}</strong><QR/><span>Scan the QR code on your bottle for immediate life-saving steps.</span></div>{!simple&&<div className="side"><h3>{page==='prevention'?'Daily Prevention Basics':page==='aftercare'?'Immediate Aftercare':'If your puppy is unresponsive'}</h3><ol>{['Warm the puppy gently but quickly.','Rub Pup-Lift on gums or under tongue.','Monitor closely and call a veterinarian.','Repeat tiny amounts every 3–5 minutes if needed.','Call your veterinarian if severe or not improving.'].map(x=><li key={x}>{x}</li>)}</ol><em>Stay calm. Act fast.</em></div>}</div></section>;
}

function Mini({icon:Icon,title,text}){return <div><Icon/><p><b>{title}</b><span>{text}</span></p></div>}
function Title({children,right}){return <div className="title"><h2>{children} <Heart size={15}/></h2>{right}</div>}
function Card({icon:Icon=Heart,title,children,tone=''}){return <article className={`card ${tone}`}><Icon className="card-icon"/><h3>{title}</h3>{children}</article>}
function Bullets({items,check=false}){return <ul className={check?'checks':'bullets'}>{items.map(x=><li key={x}>{check?<Check/>:<span/>}{x}</li>)}</ul>}
function Ribbon({labels}){const icons=[Droplets,Eye,Syringe,HeartPulse,ShieldCheck,AlertTriangle,Clock3,Thermometer,PawPrint,PillBottle,CalendarDays];return <section className="ribbon">{labels.map((l,i)=>{const I=icons[i%icons.length];return <div key={l}><I/><span>{l}</span></div>})}</section>}
function Ordered({items}){return <ol className="ordered">{items.map((x,i)=><li key={x}><b>{i+1}</b>{x}</li>)}</ol>}

function HomePage({go}){return <><Ribbon labels={['What Hypoglycemia Is','Signs to Look For','How to Administer Pup-Lift','What to Do After','Prevention Tips','Important Disclaimer']}/><div className="grid three"><Card title="1. What Is Hypoglycemia?" icon={Droplets}><p>Hypoglycemia is dangerously low blood sugar. In tiny puppies—especially toy Chihuahuas—it can happen suddenly and progress quickly.</p><div className="note"><PawPrint/>It is a medical emergency. Quick action can save your puppy’s life.</div></Card><Card title="2. Common Causes" icon={PawPrint}><Bullets items={['Missed meals or not eating enough','Stress or excitement','Getting chilled','Overexertion','Illness or infection','Poor intake','Vomiting or diarrhea']}/></Card><Card title="3. Warning Signs" icon={AlertTriangle}><Bullets items={['Weakness','Wobbling','Crying','Lethargy','Cold body','Glassy eyes','Tremors or shaking','Collapse','Seizures','Unresponsiveness']}/></Card></div><div className="grid three"><Card title="4. How to Administer Pup-Lift" icon={Syringe}><Ordered items={['Shake gently. Remove cap and ensure dropper tip is clean.','Place a small amount on the gums or under tongue.','Do not force large amounts if swallowing is poor.','Repeat tiny amounts every few minutes as needed.','Once alert, offer a small meal.']}/></Card><Card title="5. After Administering" icon={HeartPulse}><Bullets check items={['Keep your puppy warm and comfortable.','Observe closely for improvement.','Offer a small meal once alert.','Continue monitoring for 30–60 minutes.','Contact your veterinarian if symptoms persist or return.']}/></Card><Card title="6. Prevention Matters" icon={ShieldCheck}><Bullets check items={['Feed small, frequent meals.','Keep your puppy warm and cozy.','Watch for early signs and act immediately.','Avoid overexertion and stress.','Monitor very small puppies extra closely.']}/></Card></div><Banner/><Journey/><FAQStrip go={go}/></>}
function LearnPage({go}){return <><Ribbon labels={['Blood Sugar','Toy Puppy Risk','Early Signs','Common Causes','When It Is Serious','What To Do']}/><div className="grid three"><Card icon={Droplets} title="What hypoglycemia means"><p>It is a dangerous drop in blood glucose. Toy puppies have small reserves, so a missed meal, cold room, stress, or illness can cause symptoms to appear fast.</p></Card><Card icon={Baby} title="Why tiny puppies are vulnerable"><Bullets items={['Small body size','Limited stored energy','Fast metabolism','Higher sensitivity to cold','Stress during transitions']}/></Card><Card icon={Eye} title="Signs to watch"><Bullets items={['Weakness or wobbling','Crying or unusual quietness','Glassy eyes','Shaking or tremors','Collapse or unresponsiveness']}/></Card></div><Stats/><Journey/><Disclaimer/><FAQStrip go={go}/></>}
function EmergencyPage({go}){return <><Ribbon labels={['Immediate Action','Step-by-Step Guide','Dose & Frequency','What Not To Do','Aftercare','Emergency Warning Signs']}/><div className="steps-grid">{['Stay Calm & Check Your Puppy','Warm the Puppy','Administer Pup-Lift','Repeat Small Amounts if Needed','Once Alert, Offer Food','Monitor Closely','Contact a Veterinarian'].map((t,i)=><Step key={t} n={i+1} title={t}/>)}</div><Warnings/><AfterFlow/><Disclaimer/><FAQStrip go={go}/></>}
function PreventionPage({go}){return <><Ribbon labels={['Feeding Schedule','Warmth & Comfort','Stress & Activity','High-Risk Situations','Prevention Supplies','Daily Monitoring']}/><div className="grid four"><Card icon={ShieldCheck} title="Why Prevention Matters"><p>Toy puppies have small glycogen reserves, little body fat, and high energy needs.</p></Card><Card icon={PawPrint} title="Feeding Schedule"><Bullets check items={['Feed small, frequent meals.','Do not skip feedings.','Follow breeder/vet instructions.','Offer food promptly after play or stress.']}/></Card><Card icon={Thermometer} title="Keep Your Puppy Warm"><Bullets check items={['Avoid chilling at all times.','Dry puppy well if damp.','Provide cozy bedding.','Avoid drafts and cold floors.']}/></Card><Card icon={HeartPulse} title="Limit Stress & Overexertion"><Bullets check items={['Avoid rough play when tired.','Prevent long periods without rest.','Reduce stress during travel.','Keep routines calm and steady.']}/></Card></div><Stats/><RiskGrid/><Routine/><Disclaimer/><FAQStrip go={go}/></>}
function AftercarePage({go}){return <><Ribbon labels={['Warmth & Rest','Food & Hydration','Monitoring','When to Call the Vet','Preventing Another Drop','Owner Notes']}/><div className="grid four"><Card icon={Heart} title="Why Aftercare Matters"><p>Even when your puppy improves, blood sugar can drop again.</p></Card><Card icon={Thermometer} title="Keep Warm & Calm"><Bullets items={['Keep wrapped in a light blanket.','Avoid chilling or drafts.','Use your body warmth.','Keep the environment quiet.']}/></Card><Card icon={PawPrint} title="Feed Once Alert"><Bullets items={['Only feed when swallowing safely.','Offer a small meal.','Use small, frequent feedings.','Do not force food.']}/></Card><Card icon={Eye} title="Watch for Returning Signs"><Bullets items={['Weakness or wobbling','Crying or glassy eyes','Trembling or shaking','Unusual sleepiness','Collapse or unresponsiveness']}/></Card></div><FastFacts/><AfterFlow/><OfferAvoid/><Warnings/><Disclaimer/><FAQStrip go={go}/></>}
function FAQPage({go}){const qs=['What is hypoglycemia in puppies?','How do I know if my puppy has hypoglycemia?','How often does hypoglycemia happen in puppies?','Is hypoglycemia covered under the health guarantee?','How is Pup-Lift different from sugar or honey?','How much Pup-Lift should I give my puppy?','How often can I repeat doses if needed?','Can I use Pup-Lift preventively?','What if my puppy won’t swallow the syrup?','When should I contact my veterinarian?','Can hypoglycemia cause long-term damage?','Should I keep Pup-Lift with me when I travel?','How should I store Pup-Lift?','Where can I learn more?'];return <div className="faq-layout"><section className="panel"><Title>Frequently Asked Questions</Title><Accordion qs={qs}/><div className="faq-bottom"><p><b>Still have questions?</b> We’re here to help!</p><button className="btn primary" onClick={()=>go('contact')}><Mail/>Contact Our Team →</button></div></section><aside className="sidebar"><Card icon={HeartPulse} title="Need Immediate Help?"><p>If your puppy is unresponsive, follow our Emergency Steps right away.</p><button className="btn primary" onClick={()=>go('emergency')}>Go to Emergency Steps →</button></Card><Card icon={PillBottle} title="Pup-Lift Always Within Reach"><Bullets check items={['Fast-acting glucose source','Easy-to-use dropper bottle','Made for tiny puppies','Designed for emergencies']}/></Card></aside></div>}
function ContactPage(){return <><div className="promise"><Mini icon={Users} title="We’re Puppy People" text="Your peace of mind matters to us."/><Mini icon={ShieldCheck} title="Trusted Guidance" text="Reliable information and support."/><Mini icon={Clock3} title="Quick Response" text="We do our best to respond within 24 hours."/><Mini icon={PawPrint} title="Here for You" text="From first questions to forever homes."/></div><div className="contact-grid"><ContactForm/><aside className="panel"><Title>Other Ways to Reach Us</Title><ContactLine icon={Mail} title="Email Us" lines={['info@swvchihuahua.com','We respond within 24 hours.']}/><ContactLine icon={Phone} title="Call or Text Us" lines={['(276) 555–0198','Mon–Fri: 9am–6pm EST','Sat: 10am–2pm EST']}/><ContactLine icon={MapPin} title="Our Location" lines={['Abingdon, Virginia','Serving families nationwide']}/><ContactLine icon={MessageCircle} title="Follow Our Journey" lines={['Stay connected for puppy updates and care tips.']} social/></aside></div><div className="never"><Puppy/><div><h2>You’re Never Alone in This.</h2><p>We’re honored to be part of your puppy’s life. Thank you for trusting Southwest Virginia Chihuahua.</p></div><em>Tiny hearts.<br/>Lifelong love. ♡</em></div></>}
function ContactForm(){const[status,setStatus]=useState('idle');const[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const payload={first_name:String(f.get('first_name')||'').trim(),last_name:String(f.get('last_name')||'').trim(),email:String(f.get('email')||'').trim(),phone:String(f.get('phone')||'').trim(),subject:String(f.get('subject')||'').trim(),message:String(f.get('message')||'').trim(),privacy_accepted:f.get('privacy_accepted')==='on',source:'puplift'};if(!payload.first_name||!payload.last_name||!payload.email||!payload.subject||!payload.message||!payload.privacy_accepted){setError('Please complete all required fields and accept the privacy policy.');return;}setStatus('sending');try{if(!supabase)throw new Error('Supabase is not configured yet. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.');const { error: dbError } = await supabase.from('contact_messages').insert(payload);if(dbError)throw dbError;e.currentTarget.reset();setStatus('sent');}catch(err){setStatus('idle');setError(err.message||'Something went wrong.');}}return <section className="panel contact-form"><Title>Send Us a Message</Title><p>Fill out the form below and we’ll get back to you as soon as possible.</p><form onSubmit={submit}><div className="split"><input name="first_name" placeholder="First Name *"/><input name="last_name" placeholder="Last Name *"/></div><input name="email" type="email" placeholder="Email Address *"/><input name="phone" type="tel" placeholder="Phone Number (Optional)"/><select name="subject"><option value="">Subject *</option><option>Pup-Lift question</option><option>Puppy care</option><option>Available puppies</option></select><textarea name="message" placeholder="Type your message here..."/><label className="agree"><input name="privacy_accepted" type="checkbox"/> I have read and agree to the Privacy Policy.</label>{error&&<div className="form-error">{error}</div>}{status==='sent'&&<div className="form-success">Message sent. Thank you — we’ll be in touch soon.</div>}<button className="btn primary" disabled={status==='sending'}>{status==='sending'?'Sending...':'Send Message →'}</button><small>♡ We treat every message with care.</small></form></section>}
function Accordion({qs}){const[open,setOpen]=useState(0);return <div className="accordion">{qs.map((q,i)=><div className={`acc ${open===i?'open':''}`} key={q}><button onClick={()=>setOpen(open===i?-1:i)}><span><PawPrint/>{q}</span><ChevronDown/></button>{open===i&&<p>{i===0?'Hypoglycemia is a dangerous drop in blood sugar levels. It can happen quickly in tiny puppies because their bodies have small energy reserves and fast metabolisms.':'Keep your puppy warm, act quickly, use small amounts only, and contact your veterinarian whenever symptoms are severe, persistent, or returning.'}</p>}</div>)}</div>}
function Step({n,title}){return <article className="step"><b>{n}</b><h3>{title}</h3><Syringe/><p>{['Check for signs and stay calm.','Wrap your puppy in a soft blanket.','Place a very small amount on gums or under tongue.','Repeat tiny amounts every 3–5 minutes.','Once awake, offer a small meal.','Watch closely for 30–60 minutes.','Call immediately for severe symptoms.'][n-1]}</p></article>}
function Stats(){return <section className="stats"><b>Statistics & Fast Facts</b><div><PawPrint/><strong>Toy breeds</strong><span>highest risk due to size</span></div><div><CalendarDays/><strong>First 6 months</strong><span>highest-risk age window</span></div><div><Droplets/><strong>80–120 mg/dL</strong><span>typical healthy range</span></div><div><HeartPulse/><strong>Around 60 mg/dL</strong><span>major concern</span></div></section>}
function Journey(){return <section><Title>A Simple Emergency Journey</Title><div className="journey">{['Notice Symptoms','Administer Pup-Lift','Warm & Monitor','Feed & Follow Up'].map((x,i)=><div key={x}><b>{i+1}</b><Heart/><h3>{x}</h3><p>Act quickly, stay calm, and continue close care.</p></div>)}</div></section>}
function Banner(){return <section className="banner"><div><h2>Preventable, But Serious</h2><p>Hypoglycemia is preventable with proper observation and care, but it can still happen.</p><div className="danger">Hypoglycemia is not covered under the health guarantee because it is considered preventable.</div></div><Puppy/><div><h2>Scan the bottle for instant instructions</h2><p>Every bottle includes a QR code that links to emergency steps.</p></div></section>}
function RiskGrid(){return <section><Title>When Risk Is Higher</Title><div className="grid six">{['Missed Meals','Cold Temperatures','Stress or Travel','Illness or Vomiting','Heavy Play','Very Small Puppies'].map(x=><Card key={x} icon={AlertTriangle} title={x}><p>Watch closely and act early.</p></Card>)}</div></section>}
function Routine(){return <section><Title>Daily Prevention Routine</Title><div className="journey five">{['Morning meal','Warmth','Midday monitoring','Evening meal','Bedtime check'].map((x,i)=><div key={x}><b>{i+1}</b><Home/><h3>{x}</h3><p>Keep routine steady.</p></div>)}</div></section>}
function FastFacts(){return <section className="stats"><b>Aftercare Fast Facts</b><div><Clock3/><strong>30–60 minutes</strong><span>monitor closely</span></div><div><PawPrint/><strong>Small meals</strong><span>stabilize recovery</span></div><div><Heart/><strong>Warm & calm</strong><span>conserve energy</span></div><div><ShieldCheck/><strong>If signs return</strong><span>contact your vet</span></div></section>}
function AfterFlow(){return <section><Title>Aftercare: What to Do Next</Title><div className="journey">{['Warm & Observe','Feed a Small Meal','Keep Monitoring','Follow Up With Vet'].map((x,i)=><div key={x}><b>{i+1}</b><Heart/><h3>{x}</h3><p>Continue careful observation.</p></div>)}</div></section>}
function OfferAvoid(){return <div className="grid two"><Card icon={PillBottle} title="What To Offer After Pup-Lift"><Bullets check items={['Small meal once fully alert.','Fresh water once safe.','Small, frequent feedings.']}/></Card><Card icon={X} title="What To Avoid" tone="red"><Bullets items={['No rough play.','No forced food or liquid.','Do not leave puppy alone.']}/></Card></div>}
function Warnings(){return <section><Title>Emergency Warning Signs</Title><div className="warning-row">{['Seizures','Collapse','Blue or Very Pale Gums','Inability to Swallow','Unresponsiveness','Repeated Episodes'].map(x=><div key={x}><AlertTriangle/><b>{x}</b><span>Immediate veterinary care is needed.</span></div>)}<aside>Call Your Vet Immediately</aside></div></section>}
function Disclaimer(){return <section className="disclaimer"><AlertTriangle/><p><b>Hypoglycemia is preventable with careful feeding, warmth, observation, and prompt action.</b><br/><span>Hypoglycemia is not covered under the health guarantee because it is considered preventable.</span></p><p>This guidance supports emergency first-aid but does not replace veterinary care.</p></section>}
function FAQStrip({go}){return <section><Title right={<button className="link" onClick={()=>go('faq')}>View All FAQs →</button>}>Frequently Asked Questions</Title><div className="grid four small">{['How often should I give it?','When should I call a vet?','Can I use it if my puppy is cold?','What if symptoms return?'].map(q=><Card key={q} icon={PawPrint} title={q}><p>Follow the emergency guide and contact your veterinarian if symptoms persist.</p></Card>)}</div></section>}
function SocialDots(){return <div className="social"><span>f</span><span>◎</span><span>♪</span><Play/></div>}
function ContactLine({icon:Icon,title,lines,social}){return <div className="contact-line"><Icon/><div><h3>{title}</h3>{lines.map(x=><p key={x}>{x}</p>)}{social&&<SocialDots/>}</div></div>}
function Footer({go,page}){return <footer><div className="footer-grid"><div><Logo swva={page==='faq'||page==='contact'}/><em>Tiny hearts. Lifelong love. ♡</em><SocialDots/></div><div><h4>Quick Links</h4>{nav.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</div><div><h4>Emergency Reminder ♡</h4><p>Act fast. Stay calm.<br/>You can save a life.</p><div className="footer-note">If your puppy is unresponsive or having seizures, seek urgent veterinary care immediately.</div></div><div><h4>Contact Us</h4><p>☎ (276) 555-0198<br/>✉ info@swvchihuahua.com<br/>⌖ Abingdon, Virginia</p></div></div><div className="copyright">© 2025 Pup-Lift.com. All rights reserved.</div></footer>}

createRoot(document.getElementById('root')).render(<App/>);
